apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gitops-test
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.init: regex:^3.10.*
    fluxcd.io/tag.podinfod: semver:~3.1
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gitops-test
  template:
    metadata:
      labels:
        app: gitops-test
    spec:
      containers:
      - name: gitops-test
        image: gcr.io/gitops-poc/static-site
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m